# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NightstoryGoTask < Formula
  desc "Task runner / simpler Make alternative written in Go"
  homepage "https://taskfile.dev"
  version "3.17.0-nightstory"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_darwin_amd64.tar.gz"
      sha256 "5b56d072956b89ecafecf805ac09ec46ed5e6b8a646d04a4dd6dd0915d54c98f"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_darwin_arm64.tar.gz"
      sha256 "0a444eafbe60d0b39711054f75a28064e3c7ecbf20ef17afe510baf3ff3b8531"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_linux_arm64.tar.gz"
      sha256 "bbf3d7631771ffc04e57566a6e607e54d3f88aafeaf5d936eaa6ca892da86ab0"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_linux_amd64.tar.gz"
      sha256 "2afe9074d3aa10bed9eac502b447d6d5e78c2ea7f30e868eaaa2537962a7d6b5"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_linux_arm.tar.gz"
      sha256 "a154668e0586ef7630e0a9adc02f08acaa036639c1d4cde5655c3c5015eb9d57"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end

  test do
    system "#{bin}/task", "--help"
  end
end
