# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NightstoryGoTask < Formula
  desc "Task runner / simpler Make alternative written in Go"
  homepage "https://taskfile.dev"
  version "3.17.0-nightstory"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_darwin_arm64.tar.gz"
      sha256 "a5d8c710d39be43022822bfee02019e183f29eed153f9ca7d20223b1ec9766fb"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_darwin_amd64.tar.gz"
      sha256 "7500d50c3df473f116e5493b56c7dec7f51793765995078067a14e07d5e97fb8"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_linux_arm64.tar.gz"
      sha256 "4804cff0a59fd573274f63d509515388e895aef3a8a5b57fc57284b303d3b213"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_linux_amd64.tar.gz"
      sha256 "7dcbb774e652ce377554692fb5d2c70f28a3e4de5a302cff5f377854faebfa71"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_linux_arm.tar.gz"
      sha256 "1a873eb00caa1398c57a873745f1b7f17580dbbbb128ced2a22cf625f0f13ca5"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end

  test do
    system "#{bin}/task", "--help"
  end
end
