# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NightstoryGoTask < Formula
  desc "Task runner / simpler Make alternative written in Go"
  homepage "https://taskfile.dev"
  version "3.17.0-nightstory"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_darwin_amd64.tar.gz"
      sha256 "c2209410935c440eb936a03ce6c1ec287e7800334e6970d80642d51b2bfa90b1"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_darwin_arm64.tar.gz"
      sha256 "e14d917746341f0301d9041059471118f93959022cd9c8ca89d9e5ff05e8e86a"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_linux_amd64.tar.gz"
      sha256 "31e7624180015b10ebf982ad734d8136ab7af56ac8b66ba7c4a0f8d30862f688"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_linux_arm.tar.gz"
      sha256 "12194586d361344aceff69fee44575bb06157123482f4a9035a8b9f508a48911"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nightstory/task/releases/download/v3.17.0-nightstory/task_linux_arm64.tar.gz"
      sha256 "8898688ba1dd3df30a9ba561dd43443a4cf4e2f8abb95fa5467365c864ea2981"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end

  test do
    system "#{bin}/task", "--help"
  end
end
